mgz0227/legado-Harmony

- entry/src/main/ets/pages/view/BookDetailPage.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfo.ets
- entry/src/main/ets/pages/view/myCenter/MyCenter.ets
- entry/src/main/resources/base/profile/main_pages.json
> 合并跳转网盘登录、小说详情页

- entry/src/main/ets/componets/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfoGrid.ets
- entry/src/main/ets/pages/view/bookShelf/cartoonPage.ets
- entry/src/main/ets/pages/view/bookShelf/novelPage.ets
- entry/src/main/ets/pages/view/bookShelf/soundPage.ets
> 添加宫格样式、下拉刷新

- entry/src/main/ets/pages/view/bookShelf/BookInfoGrid.ets
- entry/src/main/ets/pages/view/bookShelf/cartoonPage.ets
- entry/src/main/ets/pages/view/bookShelf/novelPage.ets
- entry/src/main/ets/pages/view/bookShelf/soundPage.ets
> 取消浏览历史宫格展示

- entry/src/main/ets/componets/bookManage/BookInfoGridManage.ets
- entry/src/main/ets/componets/bookManage/BookInfoManage.ets
- entry/src/main/ets/componets/bookManage/bookListManage.ets
- entry/src/main/ets/componets/dataList/bookList.ets
- entry/src/main/ets/pages/view/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfo.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfoGrid.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/cartoonPage.ets
- entry/src/main/ets/pages/view/bookShelf/novelPage.ets
- entry/src/main/ets/pages/view/bookShelf/soundPage.ets
> 管理书籍界面和书架公用组件分离

- entry/src/main/ets/pages/view/BookEditor/BookEditorPage.ets
- entry/src/main/ets/pages/view/BookEditor/BookEditorType/BookEditorType.ets
- entry/src/main/ets/pages/view/BookEditor/InputComponet/inputComponet.ets
- entry/src/main/ets/pages/view/search/SearchBookList.ets
> add BookEitorPage.ets

- entry/src/main/ets/pages/Index.ets
> 修复Tab图标显示不全

- entry/src/main/ets/componets/bookDetail/BookOverlay.ets
- entry/src/main/ets/componets/dataList/folderList.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfo.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfoGrid.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderManages.ets
- entry/src/main/ets/pages/view/bookShelf/cartoonPage.ets
- entry/src/main/ets/pages/view/bookShelf/novelPage.ets
- entry/src/main/ets/pages/view/bookShelf/soundPage.ets
- entry/src/main/ets/storage/bookListData.ets
- entry/src/main/ets/viewData/bookData.ets
> 首页、管理页面文件夹展示切换宫格和列表

- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newBookShelf.ets
> 管理界面-新建书单页面

- entry/src/main/ets/componets/common/hideDialog.ets
- entry/src/main/ets/componets/dataList/folderList.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderManages.ets
- entry/src/main/ets/viewData/bookData.ets
> 管理页隐藏文件、隐藏弹窗

- entry/src/main/ets/componets/common/confirmDialog.ets
- entry/src/main/ets/componets/panel/catalogMove.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfo.ets
- entry/src/main/ets/pages/view/bookShelf/BookInfoGrid.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderManages.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/bookListManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newBookShelf.ets
> 小说删除删除填充添加是否删除本地缓存选项

- entry/src/main/ets/componets/group/groupTypePanel.ets
- entry/src/main/ets/pages/Index.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/myCenter/MyCenter.ets
> 优化分组标签、我的设置部分遮挡

- .github/workflows/AutoMerge.yml
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
> indexShelf切换分组

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/dialog/FolderInfoDialog.ets
- entry/src/main/ets/pages/welcomePage.ets
- entry/src/main/ets/storage/appData.ets
- entry/src/main/ets/storage/groupData.ets
- entry/src/main/ets/storage/shelfListData.ets
> 分组弹窗功能缓存本地，重命名、置顶、删除

- entry/src/main/ets/componets/common/TitleContentDialog.ets
- entry/src/main/ets/pages/view/dialog/FolderInfoDialog.ets
添加通用自定义弹窗标题、提示内容弹窗，分组弹窗隐藏、解散分组弹窗功能
> 添加通用自定义弹窗标题、提示内容弹窗，分组弹窗隐藏、解散分组弹窗功能

- entry/src/main/ets/componets/head/IndexSearchType.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/bookListManage.ets
- entry/src/main/ets/pages/view/dialog/FolderManageDialog.ets
> 书架分组单点底部弹窗书籍信息

- entry/src/main/ets/pages/view/Reader/chapterCommon.ets
- entry/src/main/ets/pages/view/Reader/sourceCommon.ets
> 单章换源-选择章节弹窗

- entry/src/main/ets/componets/head/BookMark.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
> 优化书架布局页签滑动切换

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/pages/view/Reader/newAddRule.ets
- entry/src/main/ets/pages/view/Reader/ruleView.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/resources/base/element/string.json
- entry/src/main/resources/en_US/element/string.json
- entry/src/main/resources/zh_CN/element/string.json
> 阅读器/净化/替换净化管理/更多/新建替换页面

- entry/src/main/ets/componets/Reader/exportRuleDialog.ets
- entry/src/main/ets/pages/view/Reader/directoryPurification.ets
- entry/src/main/ets/pages/view/Reader/newAddRule.ets
- entry/src/main/ets/pages/view/Reader/ruleView.ets
- entry/src/main/resources/base/element/string.json
- entry/src/main/resources/en_US/element/string.json
- entry/src/main/resources/zh_CN/element/string.json
> 阅读器/净化/替换净化管理页面完成

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/common/utils/DataPreferencesUtils.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/cartoonPage.ets
- entry/src/main/ets/pages/view/bookShelf/novelPage.ets
- entry/src/main/ets/pages/view/bookShelf/soundPage.ets
- entry/src/main/ets/preferences/bookDataPreferences.ets
- entry/src/main/ets/storage/appData.ets
- entry/src/main/ets/storage/bookListData.ets
> 数据持久化动态更新页面数据

- entry/src/main/ets/common/utils/FileHandler.ets
- entry/src/main/ets/pages/view/Find/IndexFind.ets
> 本地选择json文件导入

- entry/src/main/ets/componets/common/Score.ets
- entry/src/main/ets/componets/dataList/BookSource.ets
- entry/src/main/ets/componets/import/ImportCommon.ets
- entry/src/main/ets/pages/view/Find/BookSource/AddSourcePage.ets
- entry/src/main/ets/pages/view/Find/BookSource/Index.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
书源管理, 导入功能完善，编辑，删除，批量删除，批量禁用/启用
> feat: 书源管理, 导入功能完善，编辑，删除，批量删除，批量禁用/启用

- entry/src/main/ets/common/utils/DbUtil.ets
- entry/src/main/ets/common/utils/utils.ets
- entry/src/main/ets/componets/common/ClassifyList.ets
- entry/src/main/ets/componets/common/Score.ets
- entry/src/main/ets/componets/dataList/BookSource.ets
- entry/src/main/ets/componets/import/ImportCommon.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/AppDatabaseUtil.ets
- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/database/entities/BookSource.ets
- entry/src/main/ets/database/entities/rule/BookInfoRule.ets
- entry/src/main/ets/database/entities/rule/ContentRule.ets
- entry/src/main/ets/database/entities/rule/ExploreRule.ets
- entry/src/main/ets/database/entities/rule/ReviewRule.ets
- entry/src/main/ets/database/entities/rule/SearchRule.ets
- entry/src/main/ets/database/entities/rule/TocRule.ets
- entry/src/main/ets/database/entities/rule/index.ets
- entry/src/main/ets/database/index.ets
- entry/src/main/ets/database/types/AppDatabaseType.ets
- entry/src/main/ets/database/types/ColumnInfo.ets
- entry/src/main/ets/entryability/EntryAbility.ets
- entry/src/main/ets/pages/view/Find/BookSource/AddSourcePage.ets
- entry/src/main/ets/pages/view/Find/BookSource/Index.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
书源管理功能改造，封装db数据结构，书源改为使用db增删改查。
> 书源管理功能改造，封装db数据结构，书源改为使用db增删改查。

- entry/src/main/ets/common/utils/DbUtil.ets
- entry/src/main/ets/componets/common/ClassifyList.ets
- entry/src/main/ets/componets/common/SideBar.ets
- entry/src/main/ets/componets/import/ImportCommon.ets
- entry/src/main/ets/database/AppDatabaseUtil.ets
- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/database/entities/BookSource.ets
- entry/src/main/ets/database/entities/BookSourcePart.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
- oh-package-lock.json5
- oh-package.json5
书源管理功能改造，只查询需要的部分，增加BookSourcePart实体类，增加单个评分弹窗
> 书源管理功能改造，只查询需要的部分，增加BookSourcePart实体类，增加单个评分弹窗

- entry/src/main/ets/database/dao/BookSourceDao.ets
> feat: 修复sql语句查询错误

- entry/src/main/ets/componets/dataList/SubscriptionContent.ets
- entry/src/main/ets/componets/import/SubscriptionImport.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/database/index.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
> 订阅源页面组件拆分、新增订阅源DB字段

- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
- entry/src/main/ets/pages/view/Find/mayAlsoLike.ets
> feat: 发现获取数据增加loading效果

- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/database/entities/rssSources.ets
- entry/src/main/ets/database/entities/rssSourcesPart.ets
- entry/src/main/ets/pages/Index.ets
- entry/src/main/ets/pages/view/Subscription.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/dialogNewSources.ets
- entry/src/main/ets/pages/view/Subscription/components/newSources.ets
- entry/src/main/ets/pages/view/Subscription/components/newSourcesNetWork.ets
1.订阅源新建订阅源功能(常规网站、订阅源)
2.订阅源页面页面数据加载
> 订阅源新建订阅源功能(常规网站、订阅源)

- entry/src/main/ets/common/LazyIDataSource/rssSourcesDataSource.ets
- entry/src/main/ets/componets/import/SubscriptionImport.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/database/entities/rssSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/dialogNewSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSourcesNetWork.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
> 订阅源db新增修改，订阅源内容布局调整

- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSourcesNetWork.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionSearch.ets
> 订阅搜索页面db搜索操作

- entry/src/main/ets/componets/common/noFind.ets
- entry/src/main/ets/database/AppDatabaseUtil.ets
- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
对表数据自段做一遍校验，若是在文件中增加了字段，则在这个表中新增这个字段。
> fix: 对表数据自段做一遍校验，若是在文件中增加了字段，则在这个表中新增这个字段。

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/componets/import/SubscriptionImport.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/preferences/programDataPreferences.ets
- entry/src/main/ets/storage/appData.ets
> 订阅源分组类型数据Preferences

- entry/src/main/ets/componets/import/SubscriptionImport.ets
- entry/src/main/ets/pages/view/Subscription/rssWebView.ets
> 校验订阅源分组名称重复无法添加

- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
- entry/src/main/ets/pages/view/Find/components/CardItem.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
- entry/src/main/ets/pages/view/Find/mayAlsoLike.ets
> feat: 解析发现列表数据

- entry/src/main/ets/componets/common/noFind.ets
- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
> feat: 解析发现列表样式更新

- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/database/entities/rssSources.ets
- entry/src/main/ets/database/entities/rssSourcesPart.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSourcesNetWork.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
- entry/src/main/ets/pages/view/Subscription/rssWebView.ets
> 刚导入或更新24小时内订阅源红点进行标记

- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
> 订阅源自定义源列表、WEB VIEW 可以新增/修改

- entry/src/main/ets/common/utils/DbUtil.ets
- entry/src/main/ets/database/AppDatabaseUtil.ets
> feat: 数据表字段新增修复

- entry/src/main/ets/database/types/BookSourceType.ets
- entry/src/main/ets/pages/view/BookDetailPage.ets
- entry/src/main/ets/pages/view/Find/CategoryList/Index.ets
- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
- entry/src/main/ets/pages/view/Find/components/CardItem.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
- entry/src/main/resources/base/profile/main_pages.json
> feat: 发现查看更多进入分类列表页面，书籍卡片跳转到详情页面

- entry/src/main/ets/componets/common/noFind.ets
- entry/src/main/ets/pages/view/Find/CategoryList/Index.ets
- entry/src/main/ets/pages/view/Find/components/AllCategory.ets
- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
- entry/src/main/ets/pages/view/Find/mayAlsoLike.ets
> feat: 发现 查看全部分类

- entry/src/main/ets/database/dao/RssSourcesHistoryDao.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/PreviewEffectImage.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
> 订阅源全部删除只留收藏夹

- entry/src/main/ets/common/utils/rssSourcesUtils.ets
- entry/src/main/ets/database/dao/RssSourcesHistoryDao.ets
- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSourcesNetWork.ets
- entry/src/main/ets/pages/view/Subscription/components/PreviewEffectImage.ets
- entry/src/main/ets/pages/view/Subscription/components/RssSourcesHistory.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionSearch.ets
> 订阅源图标没有设置或则未找到资源默认用预设图标

- entry/src/main/ets/componets/source/SourceCommon.ets
- entry/src/main/ets/componets/source/SourceView.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/database/entities/BookSource.ets
- entry/src/main/ets/database/entities/BookSourcePart.ets
- entry/src/main/ets/pages/view/Find/BookSource/AddSourcePage.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
- entry/src/main/ets/pages/view/Find/components/CardItem.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
- entry/src/main/ets/storage/findData.ets
> feat: 发现 筛选操作，置顶，显示，隐藏

- entry/src/main/ets/componets/import/ImportCommon.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
> feat: 导入，书源管理操作后更新发现页面

- entry/src/main/ets/componets/source/SourceView.ets
- entry/src/main/ets/database/entities/BookSource.ets
- entry/src/main/ets/pages/view/Find/BookSource/AddSourcePage.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
> fix: 修复源类型展示

- entry/src/main/ets/componets/common/SideBar.ets
- entry/src/main/ets/componets/source/SourceView.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/database/entities/BookSource.ets
- entry/src/main/ets/database/entities/BookSourcePart.ets
- entry/src/main/ets/database/types/BookSourceType.ets
- entry/src/main/ets/pages/view/Find/BookSource/AddSourcePage.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
- entry/src/main/ets/pages/view/Find/components/ContentRefresh.ets
> feat: 下拉框选项选中状态修复

- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfoGrids.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
> 长按书架书籍弹窗删除功能

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/componets/common/InsideCircleIcon.ets
- entry/src/main/ets/componets/group/GroupType.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookSelectGroupDialog.ets
- entry/src/main/ets/storage/bookListData.ets
书架长按底部弹窗、置顶功能、移动分组功能、新建分组功能、同步刷新书架分组
> 书架长按底部弹窗、置顶、移动分组、新建分组、同步刷新书架分组

- entry/src/main/ets/common/utils/bookGroupUtils.ets
- entry/src/main/ets/componets/bookDetail/BookOverlay.ets
- entry/src/main/ets/componets/group/GroupType.ets
- entry/src/main/ets/componets/group/groupTypePanel.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/BookGroupsDao.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/database/entities/BookGroups.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderManages.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/bookListManage.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookBodyContent.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookSelectGroupDialog.ets
- entry/src/main/ets/pages/view/coverInfoImageShow.ets
- entry/src/main/ets/pages/view/dialog/FolderInfoDialog.ets
- entry/src/main/ets/pages/view/dialog/coverInfoDialog.ets
> 书架分组db操作显示，管理页面跳转分组操作功能实现

- entry/src/main/ets/database/dao/BookSourceDao.ets
- entry/src/main/ets/pages/view/Find/BookSource/components/SourceView.ets
> feat: 批量打分

- entry/src/main/ets/common/utils/bookGroupUtils.ets
- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/BookGroupsDao.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/database/entities/BookGroups.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/components/catalogAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookSelectGroupDialog.ets
> 新建书单组件化，增加分组目录批量转移db操作

- entry/src/main/ets/componets/group/groupTypePanel.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/components/catalogAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfoGrids.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookManageDialog.ets
> 分组页面管理按钮->隐藏功能

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/common/utils/bookGroupUtils.ets
- entry/src/main/ets/database/dao/BookGroupsDao.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newBookShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/components/catalogAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Shelf/WorksBookLists.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookManageDialog.ets
- entry/src/main/ets/storage/bookListData.ets
> 管理页面支持分组下的书籍添加到书单中

- entry/src/main/ets/componets/common/ReadShow.ets
- entry/src/main/ets/database/dao/BookHistoryDao.ets
- entry/src/main/ets/pages/view/BookDetailPage.ets
> 优化启动最近阅读弹窗查询优化

- commons/colorLibrary/src/main/resources/base/element/string.json
- entry/src/main/ets/pages/view/dialog/shareWorksBook.ets
> 优化书单分享图片保存

- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/pages/view/Subscription/rssWebView.ets
> 订阅源新增时候闪退bug

- entry/src/main/ets/componets/group/groupTypePanel.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
> 分组管理页面预览书籍闪退Bug修复

- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/componets/group/GroupTypeSearch.ets
- entry/src/main/ets/componets/group/groupTypePanel.ets
- entry/src/main/ets/componets/group/groupTypeSearchPanel.ets
- entry/src/main/ets/componets/head/IndexSearchType.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/database/entities/Books.ets
- entry/src/main/ets/database/types/BooksType.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/dialogNewSources.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
- entry/src/main/ets/pages/view/bookShelf/BookFolder.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/newBookShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/components/catalogAddShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Shelf/WorksBookLists.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookBodyContent.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContent.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookManageDialog.ets
- entry/src/main/ets/pages/view/dialog/worksBookInfoDialog.ets
> fix:书架书籍添加排序功能、优化布局

- entry/src/main/ets/common/utils/BookHistoryUtils.ets
- entry/src/main/ets/pages/view/Find/components/BodyContent.ets
- entry/src/main/ets/pages/view/Find/components/CardItem.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookHistoryInfo.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfoGrids.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
> 浏览历史加入书架和移除书架功能

- entry/src/main/ets/common/utils/FileHandler.ets
- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/database/entities/Books.ets
- entry/src/main/ets/pages/view/Find/CategoryList/Index.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookManageDialog.ets
1.书架书单信息导入书架;
2.优化书籍导入弹窗布局;
3.调整ReadJSONFile方法可通用读取文件获取数据
> 1.书架书单信息导入书架;2.优化书籍导入弹窗布局;3.调整ReadJSONFile方法可通用读取文件获取数据

- entry/src/main/ets/common/LazyIDataSource/BasicDataSource.ets
- entry/src/main/ets/common/LazyIDataSource/ChaptersDataSource.ets
- entry/src/main/ets/common/LazyIDataSource/FileListDataSource.ets
- entry/src/main/ets/componets/group/GroupTypeSearch.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/pages/view/BookDetailPage.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/bookListManage.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContent.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookHistoryInfo.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookManageDialog.ets
1.书架书籍改为懒加载,
2.增加页面书籍分页查询,
3.批量管理界面书籍操作页面操作数据100条(后续会增加条件搜索和组件分组筛选)
4.新增通用懒加载类,
> 书架书籍改为懒加载,增加页面书籍分页查询,批量管理界面书籍操作页面操作数据100条,新增通用懒加载类,

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/common/utils/FileHandler.ets
- entry/src/main/ets/common/utils/SystemUtils.ets
- entry/src/main/ets/common/utils/ToolsUtils.ets
- entry/src/main/ets/common/utils/booksUtils.ets
- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/BooksDao.ets
- entry/src/main/ets/database/entities/Books.ets
- entry/src/main/ets/database/entities/rssSources.ets
- entry/src/main/ets/pages/view/BookDetailPage.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/WebSetup.ets
- entry/src/main/ets/pages/view/Subscription/components/WebSetupUA.ets
- entry/src/main/ets/pages/view/Subscription/rssWebView.ets
- entry/src/main/ets/pages/view/bookShelf/IndexShelf.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/BookManagePage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookFolderManages.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoGridManage.ets
- entry/src/main/ets/pages/view/bookShelf/Manage/bookManage/BookInfoManage.ets
- entry/src/main/ets/pages/view/bookShelf/Shelf/WorksBookListGrid.ets
- entry/src/main/ets/pages/view/bookShelf/Shelf/WorksBookListInfo.ets
- entry/src/main/ets/pages/view/bookShelf/Shelf/WorksBookLists.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContent.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfoGrids.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
- entry/src/main/ets/pages/view/bookShelf/components/dialog/BookInfoDialogs.ets
- entry/src/main/ets/preferences/programDataPreferences.ets
- entry/src/main/ets/storage/appData.ets
1.订阅源Web页面刷新、分享、跳转浏览器、UA设置
2.书架管理页面布局优化
3.添加UA数据持久化
4.书籍封面如本地添加本地标识
> 1.订阅源Web页面刷新、分享、跳转浏览器、UA设置 2.书架管理页面布局优化 3.添加UA数据持久化

- entry/src/main/ets/common/utils/ClickUtils.ets
- entry/src/main/ets/componets/common/ReadShow.ets
- entry/src/main/ets/componets/search/SearchBookItem.ets
- entry/src/main/ets/pages/view/Find/components/CardItem.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookHistoryInfo.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfoGrids.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookInfos.ets
> 书架防止重复点击多次跳转

- entry/src/main/ets/common/model/BookChapter.ets
- entry/src/main/ets/common/model/XmlAnalysis.ets
- entry/src/main/ets/common/model/taskSearchBook.ets
- entry/src/main/ets/common/utils/searchUtils.ets
- entry/src/main/ets/componets/search/SearchBookItem.ets
- entry/src/main/ets/componets/search/SearchBookList.ets
- entry/src/main/ets/componets/search/SearchHead.ets
- entry/src/main/ets/database/entities/Books.ets
- entry/src/main/ets/pages/view/BookDetailPage.ets
- entry/src/main/ets/pages/view/bookShelf/components/BookContentRefresh.ets
- entry/src/main/ets/pages/view/search/SearchBook.ets
> 解决搜索结果过多导致堆栈闪退

- entry/src/main/ets/pages/view/myCenter/WebDav.ets
> WebDav账号类型替换Email或PhoneNumber

- entry/src/main/ets/common/constants/CommonConstants.ets
- entry/src/main/ets/common/model/XmlAnalysis.ets
- entry/src/main/ets/pages/view/Find/CategoryList/Index.ets
- entry/src/main/ets/pages/view/Find/components/BookFindContent.ets
> feat: 更改解析请求地址

- entry/src/main/ets/componets/import/SubscriptionImport.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
> 订阅源-收藏-取消重命名、删除功能

- entry/src/main/ets/database/dao/RssSourcesHistoryDao.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
- entry/src/main/resources/base/element/string.json
- entry/src/main/resources/en_US/element/string.json
- entry/src/main/resources/zh_CN/element/string.json
> 订阅源->批量管理->实现全选、取消全选、单项选中

- entry/src/main/ets/database/dao/SubscriptionDao.ets
- entry/src/main/ets/pages/view/Subscription/SubscriptionIndex.ets
> 订阅源->批量管理->删除功能

- entry/src/main/ets/database/AppDatabase/index.ets
- entry/src/main/ets/database/dao/rssSourceGroupDao.ets
- entry/src/main/ets/database/entities/RssSourceGroup.ets
- entry/src/main/ets/database/index.ets
- entry/src/main/ets/pages/view/Subscription/RssSources/newSources.ets
- entry/src/main/ets/pages/view/Subscription/components/SubscriptionContent.ets
> 订阅源分组改为数据库存储

- entry/src/main/ets/pages/Index.ets
- entry/src/main/resources/base/media/SUB_theme.svg
1.修复Tab切换时订阅源图标闪烁的问题
2.优化Tab页面切换逻辑
> 修复Tab切换时订阅源图标闪烁的问题
